name = "Pinetheme"
license = "CC0"
licenselink = "https://creativecommons.org/publicdomain/zero/1.0/legalcode"
description = ""
homepage = "https://pine64.org/"
tags = []
features = []
min_version = "0.59.1"

[author]
  name = ""
  homepage = ""